### ISSUE TITLE
max() arg is an empty sequence

### ISSUE THREAD

**Issue by ParetoOptimalDev** [cursorless-dev/cursorless-talon#153]
Talon: v0.2.0-305-g968a (305)
Knausj: 3e57e0165257cf07b0e21880d44a91e79cb3ef16
pokey/talon: 0.2.0
pokey/parse-tree: 0.14.0
pokey/cursorless: 0.25.271

```
2022-02-02 20:55:56 DEBUG User modules loaded at 1.6050s
2022-02-02 20:55:57    IO dired-mode
2022-02-02 20:55:58  INFO (SpeechSystem) Activating speech engine: W2lEngine(fast Conformer b108 (2021-09-15))
2022-02-02 20:55:58    IO Error finding color enablement; falling back to full enablement
2022-02-02 20:55:58    IO Traceback (most recent call last):
2022-02-02 20:55:58    IO   File "/home/nixos/.talon/user/cursorless-talon/src/marks/vscode_settings.py", line 59, in vscode_get_setting_with_fallback
    return actions.user.vscode_get_setting(key, default_value), False
2022-02-02 20:55:58    IO   File "talon/scripting/actions.py", line 78, in __call__
2022-02-02 20:55:58    IO   File "talon/scripting/types.py", line 383, in call
2022-02-02 20:55:58    IO   File "/home/nixos/.talon/user/cursorless-talon/src/marks/vscode_settings.py", line 33, in vscode_get_setting
    path: Path = actions.user.vscode_settings_path()
2022-02-02 20:55:58    IO   File "talon/scripting/actions.py", line 78, in __call__
2022-02-02 20:55:58    IO   File "talon/scripting/types.py", line 383, in call
2022-02-02 20:55:58    IO   File "/home/nixos/.talon/user/cursorless-talon/src/marks/vscode_settings.py", line 89, in vscode_settings_path
    return pick_path(
2022-02-02 20:55:58    IO   File "/home/nixos/.talon/user/cursorless-talon/src/marks/vscode_settings.py", line 68, in pick_path
    return max(existing_paths, key=lambda path: path.stat().st_mtime)
2022-02-02 20:55:58    IO ValueError: max() arg is an empty sequence
2022-02-02 20:55:58    IO Error finding shape enablement; falling back to full enablement
2022-02-02 20:55:58    IO Traceback (most recent call last):
2022-02-02 20:55:58    IO   File "/home/nixos/.talon/user/cursorless-talon/src/marks/vscode_settings.py", line 59, in vscode_get_setting_with_fallback
    return actions.user.vscode_get_setting(key, default_value), False
2022-02-02 20:55:58    IO   File "talon/scripting/actions.py", line 78, in __call__
2022-02-02 20:55:58    IO   File "talon/scripting/types.py", line 383, in call
2022-02-02 20:55:58    IO   File "/home/nixos/.talon/user/cursorless-talon/src/marks/vscode_settings.py", line 33, in vscode_get_setting
    path: Path = actions.user.vscode_settings_path()
2022-02-02 20:55:58    IO   File "talon/scripting/actions.py", line 78, in __call__
2022-02-02 20:55:58    IO   File "talon/scripting/types.py", line 383, in call
2022-02-02 20:55:58    IO   File "/home/nixos/.talon/user/cursorless-talon/src/marks/vscode_settings.py", line 89, in vscode_settings_path
    return pick_path(
2022-02-02 20:55:58    IO   File "/home/nixos/.talon/user/cursorless-talon/src/marks/vscode_settings.py", line 68, in pick_path
    return max(existing_paths, key=lambda path: path.stat().st_mtime)
2022-02-02 20:55:58    IO ValueError: max() arg is an empty sequence
2022-02-02 20:55:58 ERROR cb error topic="ready" cb=<function on_ready at 0x7fae65c94ca0>
   15:                         lib/python3.9/threading.py:930* # loader thread
   14:                         lib/python3.9/threading.py:973* 
   13:                         lib/python3.9/threading.py:910* 
   12:                            app/resources/loader.py:805| 
   11:                            app/resources/loader.py:755| 
   10:                        talon/scripting/dispatch.py:105| 
    9:                        talon/scripting/dispatch.py:144| 
    8:                        talon/scripting/dispatch.py:135| 
    7: ------------------------------------------------------# loader thread
    6:                            talon/scripting/rctx.py:233| # 'ready' user.cursorless-talon.src.marks.mark:on_ready()
    5:            user/cursorless-talon/src/marks/mark.py:223| vscode_settings_path: Path = actions.u..
    4:                         talon/scripting/actions.py:78 | 
    3:                           talon/scripting/types.py:383| 
    2: user/cursorless-talon/src/marks/vscode_settings.py:89 | return pick_path(
    1: user/cursorless-talon/src/marks/vscode_settings.py:68 | return max(existing_paths, key=lambda path: path.stat().st_mtime)
ValueError: max() arg is an empty sequence
```

**Comment by ParetoOptimalDev** [comment]
I just installed vscode and didn't have a `~/.config/Code/User/settings.json` file. This seemed to fix things:

```
echo "{}" > ~/.config/Code/User/settings.json
```

At least no errors on talon startup, will report back after trying more stuff.

**Comment by pokey** [comment]
Yes sorry that's a known issue that should be fixed soon. Just to check: was everything still working even though you had this error in your logs?
